### PR TITLE
fix(wayland): bind draw buffers to the window instead of the shm_context

### LINKED ISSUE #8872: creating window for 2nd display in wayland gives segmentation error.
### LVGL version

v9.3

### Platform

Raspberry PI 5 wayland 2 displays DSI and HDMI

### What happened?

I try to use 2 displays with the wayland driver.
The cb_flush callback crashes with a segmentation fault when copying to the draw buffer.
Tracing the code it looks like the the draw buffer created for each window is stored in the same pointer.
Should this be changed to a pointer per window to support 2 displays?
An other thing is the size of the buffer if you change the size of the window in wayland what will happen? Right now I set the size to full screen that is working ok for a single display.
The third issue is that the window (when set to fullscreen) is set to a random display. You should be able to specify the wl_output for the specific screen you want to use, but this is a relative simple change which I added my self.
My main question is about the draw buffer which is overwritten by lv_wayland_shm_create_draw_buffers maybe better to store the buffer in the window struct.

```
lv_result_t lv_wayland_shm_create_draw_buffers(shm_ctx_t * context, struct window * window)
{

    const uint32_t stride = lv_draw_buf_width_to_stride(window->width, lv_display_get_color_format(window->lv_disp));

    context->lv_draw_buf = lv_draw_buf_create(window->width, window->height / LVGL_DRAW_BUFFER_DIV,
                                              lv_display_get_color_format(window->lv_disp), stride);
    return LV_RESULT_OK;
}
```

If I switch to framebuffer, I can use two displays. But it would be nice to run in wayland. 

### How to reproduce?

```
	char title[80];
	strcpy(title, "sdrberry");

	lv_display_t *disp_0 = init_wayland(title, 1280, 720, true, false, 0);
	encoder_indev_t = lv_wayland_get_pointer(disp_0);
	main_screen = lv_display_get_screen_active(disp_0);

	screenWidth = lv_display_get_horizontal_resolution(disp_0);
	screenHeight = lv_display_get_vertical_resolution(disp_0);

	lv_display_t *disp_1 = init_wayland(title, 1280, 720,true, false, 1); // 1024, 768
	second_screen = lv_display_get_screen_active(disp_1);
```

the 0 and 1 in init_wayland tells which wl_output (display) to use, this is a customization.

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Fixes #8872 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — DISMISSED** [review]

File: src/drivers/wayland/lv_wayland_private.h [hunk 1]
```diff
@@ -198,8 +197,11 @@ struct window {
     lv_indev_t * lv_indev_touch;
     lv_indev_t * lv_indev_keyboard;
 
-    lv_wayland_display_close_f_t close_cb;
+#if !LV_WAYLAND_USE_DMABUF
+    lv_draw_buf_t * lv_draw_buf;
+#endif /*!LV_WAYLAND_USE_DMABUF*/
```
Comment (liamHowatt) [inline src/drivers/wayland/lv_wayland_private.h]: Does it build if `LV_WAYLAND_USE_DMABUF` is enabled? lv_wl_shm.c accesses it regardless of `LV_WAYLAND_USE_DMABUF`.

Comment (AndreCostaaa) [reply src/drivers/wayland/lv_wayland_private.h]: Nice one. We can almost get rid of the SHM dependency when dmabuf is enabled but not quite so let's use a bit more memory instead of wrapping 99% of its functions with `#if !LV_WAYLAND_USE_DMABUF`

File: src/drivers/wayland/lv_wl_shm.c [hunk 2]
```diff
@@ -156,36 +157,37 @@ lv_result_t lv_wayland_shm_resize_window(shm_ctx_t * context, struct window * wi
...
+    lv_display_set_draw_buffers(display, window->lv_draw_buf, NULL);
     return LV_RESULT_OK;
 }
 
 void lv_wayland_shm_delete_draw_buffers(shm_ctx_t * context, struct window * window)
 {
-    LV_UNUSED(window);
-    lv_draw_buf_destroy(context->lv_draw_buf);
+    LV_UNUSED(context);
+    if(window->lv_draw_buf) lv_draw_buf_destroy(window->lv_draw_buf);
```
[the remark this answers is not in the document]
Comment (AndreCostaaa) [reply src/drivers/wayland/lv_wl_shm.c:190]: It's okay

**Review by kisvegabor — APPROVED** [review]

**Review by uLipe — APPROVED** [review]
