### PR TITLE
fix(textarea): scroll to position when style changes

### LINKED ISSUE #9210: textarea alignment anomaly
### LVGL version

v9.4.0

### Platform

all

### What happened?

Image

@liujp-arch It should be caused by #8548.   After commenting out the code below, it works normally.

https://github.com/lvgl/lvgl/blob/ebce44ddb032138fef542f8eebffe8f6c1a75e7a/src/widgets/textarea/lv_textarea.c#L1002-L1007

### How to reproduce?

```c
int main(void) {
  lv_display_t *display;
  lv_init();

  display = lv_sdl_window_create(800, 480);
  lv_sdl_window_set_title(display, "LVGL Simulator");
  lv_sdl_mouse_create();

  lv_obj_t * textarea=lv_textarea_create(lv_screen_active());
  lv_textarea_set_text(textarea, "Type here...");
  lv_obj_set_width(textarea, 100);
  lv_obj_center(textarea);
  while (1)
  {
    uint32_t time_until_next = lv_timer_handler();
    lv_delay_ms(time_until_next);
  }
}
```

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Fixes #9210 

Before:

image

After:

image

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

File: src/widgets/textarea/lv_textarea.c [hunk 1]
```diff
@@ -1485,6 +1486,7 @@ static void lv_textarea_scroll_to_cusor_pos(lv_obj_t * obj, int32_t pos)
     lv_textarea_t * ta = (lv_textarea_t *)obj;
 
     lv_point_t cur_pos;
+    lv_obj_update_layout(ta->label);
```
Comment (kisvegabor) [inline src/widgets/textarea/lv_textarea.c:1489]: Do we need it? `LV_EVENT_SIZE_CHANGED` should update the cursor position when deferred size calculation happened?

Comment (AndreCostaaa) [reply src/widgets/textarea/lv_textarea.c:1489]: We do as the label now only updates the size when we update its layout. It's a recent change

**Review by FASTSHIFT — APPROVED** [review]
