### PR TITLE
fix(opengles): update fb address after reshaping texture

### LINKED ISSUE #9100: DRM+EGL: Heap use after free due to realloc
### LVGL version

v9.4.0

### Platform

DRM+EGL on Linux.

### What happened?

This happens when `LV_USE_DRAW_OPENGLES` is 0.
In `lv_linux_drm_egl.c`:
In `lv_linux_drm_set_file`, `lv_opengles_texture_create_draw_buffers` is called, then `lv_opengles_texture_reshape`.
In `lv_opengles_texture.c`:
`lv_opengles_texture_create_draw_buffers` calls `lv_display_set_buffers` using allocated memory.
`lv_opengles_texture_reshape` calls realloc on previous allocated memory -> address changes (or at least may change).
The buffer being used is the pre-realloc address.
The fix seems to be to call `lv_display_set_buffers` again in `lv_opengles_texture_reshape`, but I am not too sure if there are some other side effects.

### How to reproduce?

Use `lv_port_linux` with `CONFIG=drm-egl-2d`.

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Fixes #9100 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

File: src/display/lv_display.h [hunk 1]
```diff
@@ -389,6 +389,13 @@ LV_ATTRIBUTE_FLUSH_READY bool lv_display_flush_is_last(lv_display_t * disp);
 
 bool lv_display_is_double_buffered(lv_display_t * disp);
 
+/**
+ * Get display render mode
+ * @param disp      pointer to a display
+ * @return      display's render mode (LV_DISPLAY_RENDER_MODE_PARTIAL/DIRECT/FULL)
+ */
```
Comment (kisvegabor) [inline src/display/lv_display.h:396]:
```suggestion
 * Get display render mode
 * @param disp      pointer to a display
 * @return          display's render mode (LV_DISPLAY_RENDER_MODE_PARTIAL/DIRECT/FULL)
 */
```

**Review by kisvegabor — APPROVED** [review]
Just fixed a minor formatting issue.

**Review by FASTSHIFT — APPROVED** [review]
