### PR TITLE
fix(label): correct cursor position calculation

### LINKED ISSUE #9083: Text area multiline moves wrongs
lvgl 8.4

Found trouble with multi line text area.
Seems that cursor can't calculate right y position.
Problem happen on character add and charatter click, with multiline text area

https://github.com/lvgl/lvgl/pull/8506#discussion_r2226073024
Copilot told us on review.

Image

Thats solution that i found:
lv_label.c
``` C
while(txt[new_line_start] != '\0') {
       //new_line_start += _lv_txt_get_next_line(&txt[line_start], font, letter_space, max_w, NULL, flag);//Remove this
        bool last_line = y + letter_height + line_space + letter_height > max_h;
        if(last_line && label->long_mode == LV_LABEL_LONG_DOT) flag |= LV_TEXT_FLAG_BREAK_ALL;

        new_line_start += _lv_txt_get_next_line(&txt[line_start], font, letter_space, max_w, NULL, flag);
        if(byte_id < new_line_start || txt[new_line_start] == '\0')
            break; /*The line of 'index' letter begins at 'line_start'*/

        y += letter_height + line_space;
        line_start = new_line_start;
}
```

### PR DESCRIPTION
**Pull request by Cookie987**
For LVGL8.4
This commit removes the duplicate line calculation to ensure the iterator advances exactly once per iteration, restoring accurate cursor positioning.

Fixes #9083

### CODE REVIEW

File: src/widgets/lv_label.c [hunk 1]
```diff
@@ -331,7 +331,8 @@ void lv_label_get_letter_pos(const lv_obj_t * obj, uint32_t char_id, lv_point_t
 
     /*Search the line of the index letter*/;
     while(txt[new_line_start] != '\0') {
-        new_line_start += _lv_txt_get_next_line(&txt[line_start], font, letter_space, max_w, NULL, flag);
+        // Removed to fix cursor position calculation
+        // new_line_start += _lv_txt_get_next_line(&txt[line_start], font, letter_space, max_w, NULL, flag);
```
Comment (AndreCostaaa) [inline src/widgets/lv_label.c]: Don't leave dead code, just remove it entirely

**Review by AndreCostaaa — CHANGES_REQUESTED** [review]

**Review by AndreCostaaa — APPROVED** [review]
