### PR TITLE
fix(flex): fix crash with flex_grow on screen

### LINKED ISSUE #168: Setting flex_grow="1" on object locks up the editor
OS: Window 11
Editor: v0.3

When using the editor, it was not clear to me what value to put in the ``flex_grow`` attribute. The editor did not suggest values that made sense to me, so I attempted setting the value to ``1``. Like so:
```xml
<screen>
    <view style_pad_all="15">
        <lv_obj width="100%" height="100%" flex_flow="row" flex_grow="1">
            <lv_button>
                <lv_label text="Test 1" />
            </lv_button>
            <lv_button>
                <lv_label text="Test 2" />
            </lv_button>
            <lv_button>
                <lv_label text="Test 3" />
            </lv_button>
            <lv_button>
                <lv_label text="Test 4" />
            </lv_button>
        </lv_obj>
    </view>
</screen>
```

As soon as I add the ``flex_grow="1"`` attribute, the editor locks up and will not allow me to continue. I can use the menu bar, but cannot even exit the application. The only to resolve is to kill the process and restart.

I'm not saying that ``flex_grow="1"`` is valid xml, but it probably shouldn't lockup the editor and put it in an unrecoverable state. Not sure if this is just my dev environment or if someone else can reproduce.

### PR DESCRIPTION
**Pull request by kisvegabor**
Fixes https://github.com/lvgl/lvgl_editor/issues/168

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by AndreCostaaa — DISMISSED** [review]

File: src/layouts/flex/lv_flex.c [hunk 1]
```diff
@@ -116,7 +116,8 @@ void lv_obj_set_flex_align(lv_obj_t * obj, lv_flex_align_t main_place, lv_flex_a
 void lv_obj_set_flex_grow(lv_obj_t * obj, uint8_t grow)
 {
     lv_obj_set_style_flex_grow(obj, grow, 0);
-    lv_obj_mark_layout_as_dirty(lv_obj_get_parent(obj));
+    lv_obj_t * parent = lv_obj_get_parent(obj);
+    if(parent) lv_obj_mark_layout_as_dirty(parent);
```
Comment (FASTSHIFT) [inline src/layouts/flex/lv_flex.c:120]: Can you add a test case to cover this scenario? The coverage report does not cover the entire branch:
3195938f-2073-4d8a-a56d-0766f8d91b94

**Review by FASTSHIFT — APPROVED** [review]

**Review by AndreCostaaa — APPROVED** [review]
