### PR TITLE
fix(vg_lite): initialize matrix before vg_lite_update_linear_grad

### LINKED ISSUE #9951: Linear gradient fails with uninitialized matrix in `linear_ext_grad_create`
### LVGL version

v9.5.0

### Platform

vg_lite

### What happened?

 When using extended linear gradient (`LV_VECTOR_GRADIENT_STYLE_LINEAR_EXT`), the gradient creation fails with `VG_LITE_INVALID_ARGUMENT` error because the transformation matrix is not initialized
  before calling `vg_lite_update_linear_grad()`.

### Log
```
[Error]    (71.028, +320)     linear_ext_grad_create: Execute 'err = vg_lite_update_linear_grad(&item->vg.linear_ext)' error: 1 lv_vg_lite_grad.c:567
  [User]    (71.041, +13)     lv_vg_lite_error_dump_info: Error code: 1(INVALID_ARGUMENT) lv_vg_lite_utils.c:106
  [User]    (71.050, +9)     lv_vg_lite_ext_linear_gradient_dump_info: count: 0 lv_vg_lite_grad.c:847
  [User]    (71.059, +9)     lv_vg_lite_matrix_dump_info: | 0.000000, 0.000000, 0.000000 | lv_vg_lite_utils.c:472
  [User]    (71.068, +9)     lv_vg_lite_matrix_dump_info: | 0.000000, 0.000000, 0.000000 | lv_vg_lite_utils.c:472
  [User]    (71.078, +10)     lv_vg_lite_matrix_dump_info: | 0.000000, 0.000000, 0.000000 | lv_vg_lite_utils.c:472
  [User]    (71.087, +9)     lv_vg_lite_buffer_dump_info: memory: 00000000 lv_vg_lite_utils.c:459
  [User]    (71.095, +8)     lv_vg_lite_buffer_dump_info: address: 0x00000000 lv_vg_lite_utils.c:460
  [User]    (71.103, +8)     lv_vg_lite_buffer_dump_info: size: W0 x H0 lv_vg_lite_utils.c:461
  [User]    (71.111, +8)     lv_vg_lite_buffer_dump_info: stride: 0 lv_vg_lite_utils.c:462
  [User]    (71.118, +7)     lv_vg_lite_buffer_dump_info: format: 0 (UNKNOWN_BUFFER_FORMAT) lv_vg_lite_utils.c:463
  [User]    (71.128, +10)     lv_vg_lite_buffer_dump_info: tiled: 0 lv_vg_lite_utils.c:466
  [User]    (71.135, +7)     lv_vg_lite_ext_linear_gradient_dump_info: linear_grad: X0: 93.000000, Y0: 211.000000, X1: 93.000000, Y1: 230.000000 lv_vg_lite_grad.c:850
  [User]    (71.149, +14)     lv_vg_lite_ext_linear_gradient_dump_info: ramp_length: 2 lv_vg_lite_grad.c:853
  [User]    (71.158, +9)     lv_vg_lite_color_ramp_dump_info: [0] stop: 0.000000, red: 0.129412, green: 0.588235, blue: 0.952941, alpha: 0.752941 lv_vg_lite_grad.c:840
  [User]    (71.172, +14)     lv_vg_lite_color_ramp_dump_info: [1] stop: 1.000000, red: 0.129412, green: 0.588235, blue: 0.952941, alpha: 0.658824 lv_vg_lite_grad.c:840
  [User]    (71.186, +14)     lv_vg_lite_ext_linear_gradient_dump_info: converted_length: 2 lv_vg_lite_grad.c:856
  [User]    (71.196, +10)     lv_vg_lite_color_ramp_dump_info: [0] stop: 0.000000, red: 0.129412, green: 0.588235, blue: 0.952941, alpha: 0.752941 lv_vg_lite_grad.c:840
  [User]    (71.210, +14)     lv_vg_lite_color_ramp_dump_info: [1] stop: 1.000000, red: 0.129412, green: 0.588235, blue: 0.952941, alpha: 0.658824 lv_vg_lite_grad.c:840
  [User]    (71.224, +14)     lv_vg_lite_ext_linear_gradient_dump_info: pre_multiplied: 1 lv_vg_lite_grad.c:859
  [User]    (71.233, +9)     lv_vg_lite_ext_linear_gradient_dump_info: spread_mode: 7168 lv_vg_lite_grad.c:860
  [Error]    (71.243, +10)     grad_item_pool_free: Asserted at expression: item->ctx != NULL (NULL pointer) lv_vg_lite_grad.c:450
```

### Root Cause

  In `lv_vg_lite_grad.c`, the `linear_ext_grad_create()` function calls `vg_lite_update_linear_grad()` without first initializing the `grad->matrix` to identity. Since the matrix is allocated but not
  initialized, it contains garbage values (all zeros in practice), causing the length calculation to fail:

  ```c
  // vg_lite.c:6106-6116
  x0 = grad->matrix.m[0][0] * grad->linear_grad.X0 + ...;  // 0 × 93 = 0
  y0 = grad->matrix.m[1][0] * grad->linear_grad.X0 + ...;  // 0 × 211 = 0
  x1 = grad->matrix.m[0][0] * grad->linear_grad.X1 + ...;  // 0 × 93 = 0
  y1 = grad->matrix.m[1][0] * grad->linear_grad.X1 + ...;  // 0 × 230 = 0

  dx = x1 - x0 = 0;
  dy = y1 - y0 = 0;
  length = sqrt(dx*dx + dy*dy) = 0;

  if (length <= 0)
      return VG_LITE_INVALID_ARGUMENT;  // Error!

  Note: The matrix is set to identity after the length check succeeds (line 6120), so it must be initialized before calling vg_lite_update_linear_grad().

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by huohongpeng**
Fixes #9951

### CODE REVIEW

File: src/draw/vg_lite/lv_vg_lite_grad.c [hunk 1]
```diff
@@ -564,6 +564,9 @@ static bool linear_ext_grad_create(grad_item_t * item, vg_lite_color_ramp_t * co
 
     LV_PROFILER_DRAW_BEGIN_TAG("vg_lite_update_linear_grad");
     vg_lite_error_t err = VG_LITE_SUCCESS;
+    vg_lite_matrix_t * mat_grad;
+    mat_grad = vg_lite_get_linear_grad_matrix(&item->vg.linear_ext);
+    vg_lite_identity(mat_grad);
     LV_VG_LITE_CHECK_ERROR(err = vg_lite_update_linear_grad(&item->vg.linear_ext), {
```
Comment (FASTSHIFT) [inline src/draw/vg_lite/lv_vg_lite_grad.c:568]: It can be simplified to one line to reduce temporary variables:
```c
vg_lite_identity(vg_lite_get_linear_grad_matrix(&item->vg.linear_ext));
```

**Review by FASTSHIFT — CHANGES_REQUESTED** [review]

File: src/draw/vg_lite/lv_vg_lite_grad.c (hunk 1 above)
Comment (huohongpeng) [reply src/draw/vg_lite/lv_vg_lite_grad.c:568]: Done

**Review by FASTSHIFT — APPROVED** [review]
