### PR TITLE
fix(obj): add missing alloc check for children and spec_attr

### LINKED ISSUE #9794: Crash when creating many child objects (unchecked realloc in "lv_obj_class_create_obj")
### LVGL version

v9.1.0 but present in master as well

### Platform

Custom ESP32-S3 keyboard with a TFT display controlled via SPI.

### What happened?

Hi, 
First of all, thank you for the great library, LVGL has been awesome to work with on our product.

We hit this while stress testing our product firmware on hardware (ESP32-S3 + LVGL 9.1.0).

### Context from our test
We were repeatedly creating LVGL widgets as part of a stress scenario.  
Once we crossed roughly **120 objects**, the board would crash almost immediately (Guru Meditation / memory corruption style failure), instead of failing gracefully with an allocation error.

The debugger consistently stops here:

```c
parent->spec_attr->children[parent->spec_attr->child_cnt - 1] = obj;
```

in `lv_obj_class_create_obj()`.

In the screen path (`parent == NULL`), realloc is checked and handled safely.

In the normal object path, realloc result is used directly:

```c
parent->spec_attr->child_cnt++;
parent->spec_attr->children = lv_realloc(parent->spec_attr->children,
                                         sizeof(lv_obj_t *) * parent->spec_attr->child_cnt);
parent->spec_attr->children[parent->spec_attr->child_cnt - 1] = obj;
```

If `lv_realloc()` returns `NULL` under pressure, this dereferences `NULL` immediately.

### Expected behavior
If memory is exhausted while growing the child array, object creation should fail cleanly (return `NULL` / log error), without crashing or corrupting state.

### Actual behavior
Hard crash on device under heavy object creation.

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Fixes #9794  

Not only this adds the missing malloc check causing the issue in #9794 but I also modified `allocate_spec_attrs` to return the structure allocated, allowing us to easily check if the allocation failed

Also moved this structure to obj_private as it's not supposed to be used by the user

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

File: src/core/lv_obj_private.h [hunk 1]
```diff
@@ -92,6 +94,18 @@ struct _lv_obj_t {
  * GLOBAL PROTOTYPES
  **********************/
 
+/**
+ * Create special data for an object.
+ */
+lv_obj_spec_attr_t * lv_obj_spec_attr_create(void);
```
Comment (kisvegabor) [inline src/core/lv_obj_private.h]: This function is called on on one place internally. Does make sense to have dedicated function for it?

Comment (AndreCostaaa) [reply src/core/lv_obj_private.h]: Separation of concerns, this one creates and initializes the structure correctly, the other function assigns it to the object if required

File: src/misc/lv_types.h [hunk 2]
```diff
@@ -188,8 +188,6 @@ typedef struct _lv_hit_test_info_t lv_hit_test_info_t;
 
 typedef struct _lv_cover_check_info_t lv_cover_check_info_t;
 
-typedef struct _lv_obj_spec_attr_t lv_obj_spec_attr_t;
-
 typedef struct _lv_image_t lv_image_t;
 
 typedef struct _lv_animimg_t lv_animimg_t;
```
[the remark this answers is not in the document]
Comment (AndreCostaaa) [reply src/misc/lv_types.h:193]: It wouldn't be accessed anyways because nothing public uses it

File: src/core/lv_obj.h [hunk 3]
```diff
@@ -313,12 +313,6 @@ void * lv_obj_get_user_data(lv_obj_t * obj);
  * Other functions
  *======================*/
 
-/**
- * Allocate special data for an object if not allocated yet.
- * @param obj   pointer to an object
- */
-void lv_obj_allocate_spec_attr(lv_obj_t * obj);
-
 /**
```
[the remark this answers is not in the document]
Comment (AndreCostaaa) [reply src/core/lv_obj.h:316]: I rather make this breaking api change, I don't see a use case for it to be called from the user code

File: src/core/lv_obj.c [hunk 4]
```diff
@@ -411,18 +411,67 @@ lv_group_t * lv_obj_get_group(const lv_obj_t * obj)
...
+        parent->spec_attr->children = NULL;
+        parent->spec_attr->child_cnt = 0;
+        return;
+    }
+
+    parent->spec_attr->child_cnt--;
+    parent->spec_attr->children = lv_realloc(parent->spec_attr->children,
+                                             parent->spec_attr->child_cnt * (sizeof(lv_obj_t *)));
+    /* Reallocating a smaller size should never fail, so assert it here*/
+    LV_ASSERT_MALLOC(parent->spec_attr->children);
```
[the remark this answers is not in the document]
Comment (AndreCostaaa) [reply src/core/lv_obj.c:452]: Only a very broken implementation of relloc would return NULL after shrinking the array

File: src/core/lv_obj_private.h (hunk 1 above)
Comment (kisvegabor) [reply src/core/lv_obj_private.h]: I don't agree with that. To me it feel like over engineering. `allocate` and `create` are very similar in meaning so they are hard to distinguish. 

Since even conceptually `create` shouldn't be used anywhere else other than inside `allocate` 
1. It should be at least `static`
2. No need to create a new function as `allcate` will remain short even if the content of `create` is added to it.

**Review by FASTSHIFT — DISMISSED** [review]

File: src/core/lv_obj_private.h (hunk 1 above)
Comment (AndreCostaaa) [reply src/core/lv_obj_private.h]: I merged them together

**Review by FASTSHIFT — APPROVED** [review]
