### PR TITLE
fix(draw/sw): check that malloc doesn't return a NULL pointer

### LINKED ISSUE #8638: Update Web Image Converter due to missing `header.stride`, at least the `img_conv` repo or release a 9.3.1
### LVGL version

v9.3.0

### Platform

Visual Studio Code, with ESP-IDF Plugin

### What happened?

Today because I open a project for ESP32 in another PC, the ESP-IDF sync again the external components, and due to a mistake i didn't block LVGL version to v9.2.2 and it downloaded the v9.3.0.

The application crashed, since I have images in format ARGB888 and issuing an recolor command, the program crashed because the images don't have the `header.stride` element. In this case the fix was simple, force LVGL version to 9.2.2 and tell ESP-IDF plugin to redownload external components...

The images were generated via `EEZ-Studio` that could be using an old version but even using the online converter or the converter from the GitHub repository that element is not being generated.

I noticed that there is already an PR merged to resolve that in the `master` branch of v9.3.0 that calculates that element in case is not present https://github.com/lvgl/lvgl/pull/8483

But even so for people that don't want to live on the `bleeding edge` and to have support for v9.3.0 would be nice if:
- The Web Image converter supported the V9.3.0 correctly
- The image converter on the GitHub repository also supports the v9.3.0 correctly

But the preferable way, would probably be:
- Release a bug fix version, v9.3.1 with this solved, in order not to force us to use a non-official version, based on the master branch that may have other issues / API breaking and that does not exist in most of the component registry for ESP, platformIO and so on... and probably to fix other `simple`issues present in v9.3.0.

Thank You

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Fixes #8638 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

File: src/draw/sw/lv_draw_sw_img.c [hunk 1]
```diff
@@ -408,6 +408,11 @@ static void recolor_only(lv_draw_task_t * t, const lv_draw_image_dsc_t * draw_ds
     buf_h = MAX_BUF_SIZE / buf_stride;
     if(buf_h > blend_h) buf_h = blend_h;
     tmp_buf = lv_malloc(buf_stride * buf_h);
+    LV_ASSERT_MALLOC(tmp_buf);
```
Comment (uLipe) [inline src/draw/sw/lv_draw_sw_img.c:411]: Why do we have ASSERT and a second check of the buffer?  I feel this code is duplicated because it:

* Handles catastrophic error : Assertion
* Handles a non-catastrophic error: Noop + Log 

This code is supposed to do only one, no?

**Review by FASTSHIFT — APPROVED** [review]

File: src/draw/sw/lv_draw_sw_img.c (hunk 1 above)
Comment (AndreCostaaa) [reply src/draw/sw/lv_draw_sw_img.c:411]: The assert is the valid choice here since we can't recover from this, we're basically out of memory. The extra check is for cases where the assert is disabled and it logs a warning and prevents a null ptr dereference afterwards. I believe it's a common pattern i've seen around the codebase

I'm open to suggestions

**Review by liamHowatt — APPROVED** [review]
