### PR TITLE
fix(dmabuf): flicker when the buffers are swapped for new frame

### LINKED ISSUE #8517: Wayland DMA Buffer wait for flushing
### LVGL version

v9.3.0

### Platform

NXP i.MX MPU

### What happened?

When LVGL is configured to use both software and G2D rendering units, along with DMA buffers, on a 1080p HDMI-connected display, visual artifacts appear and the LVGL window flickers.

After enabling Wayland debug flags, I observed that LVGL begins buffer swapping and drawing immediately after `lv_wayland_wait_flush_cb` completes. However, the `buffer_release` callback from Wayland is triggered *after* LVGL starts drawing.

This indicates a synchronization issue: LVGL should wait for the `buffer_release` signal before acquiring a buffer for rendering. Without this wait, drawing begins when the buffer is still used by the compositor, leading to flickering and display artifacts.

From my point of view, the `acquire` function should be called by LVGL when the buffers are swapped, not by `flush`. In this way, the buffers will be busy until wayland releases them, and drawing will begin only after `buffer_release` signal is received.

I believe fixing this issue may require some changes on the `lv_refr` side, so I'd appreciate your input on how best to approach it.

@AndreCostaaa @kisvegabor do you have any ideas on how we could approach fixing this?

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by cosmindanielradu19**
Fixes #8517 

This will be rebased after #8406 will be merged.

@kisvegabor @AndreCostaaa please take a look

This PR introduces a new callback that is invoked after the buffer is flushed to the display. It allows you to wait until a buffer becomes available before performing another swap and draw operation.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
I believe we can do this with the existing functionality as well. We can add an `LV_EVENT_REFR_START` event to the display. 
It's called even if there is nothing the render at the beginning of each rendering. So we can do something like:
```c
void even_cb(lv_evene_t *e) {
   lv_display_t * disp = lv_event_get_target(e);
   if(disp->inv_p == 0) return; //No rendering will happen
   wait_for_swapping(disp);
}
```

File: src/core/lv_refr.c [hunk 1]
```diff
@@ -1380,6 +1381,11 @@ static void draw_buf_flush(lv_display_t * disp)
     if(disp->flush_cb) {
         call_flush_cb(disp, &disp->refreshed_area, layer->draw_buf->data);
     }
+
```
Comment (cosmindanielradu19) [inline src/core/lv_refr.c]: @kisvegabor what if the wait for swapping is moved under the swap condition?

```suggestion
    /*If there are 2 buffers swap them. With direct mode swap only on the last area*/
    if(lv_display_is_double_buffered(disp) && (disp->render_mode != LV_DISPLAY_RENDER_MODE_DIRECT || flushing_last)) {
        wait_for_swapping(disp);
        if(disp->buf_act == disp->buf_1) {
            disp->buf_act = disp->buf_2;
        }
```

I believe that the flush time will not be reported correctly if `disp_event_cb` is used for this.

File: src/drivers/wayland/lv_wayland_private.h [hunk 2]
```diff
@@ -77,6 +77,10 @@ enum object_type {
 #define LAST_DECORATION (OBJECT_BORDER_RIGHT)
 #define NUM_DECORATIONS (LAST_DECORATION - FIRST_DECORATION + 1)
 
+#if LV_WAYLAND_USE_DMABUF
+#define MAX_BUFFER_PLANES 4
```
Comment (uLipe) [inline src/drivers/wayland/lv_wayland_private.h]: Is this a hard constraint? If not, it can be turned into a LV configuration symbol to allow the application to select it.

File: src/display/lv_display.c [hunk 3]
```diff
@@ -550,6 +550,14 @@ void lv_display_set_flush_wait_cb(lv_display_t * disp, lv_display_flush_wait_cb_
     disp->flush_wait_cb = wait_cb;
 }
 
+void lv_display_set_swap_buf_wait_cb(lv_display_t * disp, lv_display_swap_buf_wait_cb_t wait_cb)
+{
+    if(disp == NULL) disp = lv_display_get_default();
+    if(disp == NULL) return;
```
Comment (uLipe) [inline src/display/lv_display.c]: I believe this kind of return could also have a LOG_WRN or LOG_ERR to make easier to debug when the things goes wrong.

**Review by uLipe — COMMENTED** [review]
Nice one! Just left some minor comments.

File: src/core/lv_refr.c (hunk 1 above)
Comment (kisvegabor) [reply src/core/lv_refr.c]: My concern is that I want to introduce a new buffer manager callback only if the current event and call back system is not suitable. 

Is there any way to use the currently available tools?

**Comment by kisvegabor** [comment]
Could [this](https://github.com/lvgl/lvgl/pull/8563#issuecomment-3061425989) work?

**Comment by cosmindanielradu19** [comment]
> Could [this](https://github.com/lvgl/lvgl/pull/8563#issuecomment-3061425989) work?

I've looked into it a 2nd time and it seems to be working fine. I've just pushed the changes.

Thanks

File: src/display/lv_display.c (hunk 3 above)
Comment (cosmindanielradu19) [reply src/display/lv_display.c]: I've noticed that the other functions that set callbacks don't include logging in case of an early return.
I believe we should either add logs to all the setters or leave them as they are for consistency.

File: src/drivers/wayland/lv_wayland_private.h (hunk 2 above)
Comment (cosmindanielradu19) [reply src/drivers/wayland/lv_wayland_private.h]: It is a fixed number

**Comment by kisvegabor** [comment]
Something is strange. 

I see that you have removed wait_for_swapping [here](https://github.com/lvgl/lvgl/pull/8563/commits/02561ee11f4f20bd5a11ad5592fd049bc25b1225#diff-67fd1b48a2bb4b3f48b602ce63408bcc5c729d6193bf05735905a7e74c0fa50cL59) but I still see it among the changes [files](https://github.com/lvgl/lvgl/pull/8563/files#diff-d5e5e7b4b434f724deeead3491cc6d37ecc20b0db8f61600d528bcdd73353ebfR49).

**Comment by cosmindanielradu19** [comment]
> Something is strange.
> 
> I see that you have removed wait_for_swapping [here](https://github.com/lvgl/lvgl/pull/8563/commits/02561ee11f4f20bd5a11ad5592fd049bc25b1225#diff-67fd1b48a2bb4b3f48b602ce63408bcc5c729d6193bf05735905a7e74c0fa50cL59) but I still see it among the changes [files](https://github.com/lvgl/lvgl/pull/8563/files#diff-d5e5e7b4b434f724deeead3491cc6d37ecc20b0db8f61600d528bcdd73353ebfR49).

I moved it from [lv_refr.c](https://github.com/lvgl/lvgl/blob/master/src/core/lv_refr.c) to [lv_display.c](https://github.com/lvgl/lvgl/blob/master/src/display/lv_display.c).

**Comment by nicusorcitu** [comment]
Hi @kisvegabor @AndreCostaaa @uLipe can you please help reviewing this PR? Thanks!

File: src/drivers/wayland/lv_wl_dmabuf.c [hunk 4]
```diff
@@ -144,6 +126,22 @@ void lv_wayland_dmabuf_on_graphical_object_destruction(dmabuf_ctx_t * context, s
...
+    if(window->frame_counter == 0) {
+        return;
+    }
+
+    int buf_nr = (window->wl_ctx->dmabuf_ctx.last_used + 1) % LV_WAYLAND_BUF_COUNT;
+
+    while(window->wl_ctx->dmabuf_ctx.buffers[buf_nr].busy) {
+        wl_display_roundtrip(lv_wl_ctx.display);
+        usleep(500); /* Sleep for 0.5ms to avoid busy waiting */
+    }
```
Comment (liamHowatt) [inline src/drivers/wayland/lv_wl_dmabuf.c:170]: Just wondering: can the `fd` be `poll`ed before calling `wl_display_roundtrip` to block until something will actually happen? That way the sleep wouldn't be needed? I don't know if it's possible.

**Review by uLipe — DISMISSED** [review]

File: src/drivers/wayland/lv_wl_dmabuf.c (hunk 4 above)
Comment (cosmindanielradu19) [reply src/drivers/wayland/lv_wl_dmabuf.c:170]: Without the `wl_display_roundtrip` I wasn't able to get the buffer released, so it will be locked here as busyif `poll` is used.

**Comment by nicusorcitu** [comment]
@cosmindanielradu19 please rebase

**Comment by cosmindanielradu19** [comment]
I've realized that LV_WAYLAND_WINDOW_DECORATIONS 0 will make the build fail with G2D and DMABUF. I've added the fix in this PR.
@AndreCostaaa please take a look 👀
Thanks

File: src/core/lv_refr.c [hunk 5]
```diff
@@ -1380,6 +1380,7 @@ static void draw_buf_flush(lv_display_t * disp)
...
```
Comment (AndreCostaaa) [inline src/core/lv_refr.c]: nit: remove this empty line that got added by mistake for a cleaner git diff

File: src/display/lv_display.c [hunk 6]
```diff
@@ -1369,4 +1378,17 @@ static void disp_event_cb(lv_event_t * e)
         default:
             break;
     }
+    if(disp->inv_p == 0) return;
+    wait_for_swapping(disp);
```
Comment (AndreCostaaa) [inline src/display/lv_display.c]: The location for this `wait_for_swapping` is suspicious, what's the exact issue?

We have 2 draw buffers, is the tearing caused by writing to the first buffer even though the second buffer has already been flushed? Isn't this already solved by the `flush_wait_cb` that is called right after flushing to the display? I don't fully understand

Comment (cosmindanielradu19) [reply src/display/lv_display.c]: LVGL draws in the 1st buffer, and that buffer is flushed to the display.
LVGL draws in the 2nd budder, and flushes it to the display. 
LVGL will start drawing in the 1st buffer, but it will do it even if the buffer_release callback didn't come for the 1st buffer.

Comment (AndreCostaaa) [reply src/display/lv_display.c]: Okay nice, so I follow you now

So I see two easier ways to handle this without having to add a new callback to `lv_display`
1. LV_EVENT_REFR_START is called before any rendering starts, meaning that we could wait for the buffers to get swapped there 
2. The `flush_wait_cb` is also called before the rendering starts so that could be an option too, check which buffer is being waited on and wait

I saw this comment 
> I believe that the flush time will not be reported correctly if disp_event_cb is used for this.

Maybe you were mentioning something else but using LV_EVENT_REFR_START doesn't take into account the flush time, doesn't one of these two options solve it for you?

Comment (cosmindanielradu19) [reply src/display/lv_display.c]: I need to check if any of the options you provided works. I'll come back with feedback after that. Thanks!

Comment (cosmindanielradu19) [reply src/display/lv_display.c]: Hi @AndreCostaaa 

I've managed to look into this and I've made some changes. Can you take a second look now? 👀

Thanks

**Review by AndreCostaaa — APPROVED** [review]
After flushing it waits until another buffer is ready

Makes sense to me. Thank you :rocket:

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thank you @cosmindanielradu19 and @AndreCostaaa!

**Comment by nicusorcitu** [comment]
@anaGrad @AndreCostaaa it looks like the flickering is back in 9.4 release.

**Comment by AndreCostaaa** [comment]
Hi @nicusorcitu In what board were you able to reproduce this issue?

FYI: I have a big wayland PR coming with the goal of completely separating SHM and G2D (and EGL in the future)

**Comment by anaGrad** [comment]
> Hi @nicusorcitu In what board were you able to reproduce this issue?

Hi @AndreCostaaa . I was able to reproduce on i.MX93 with dmabuf, it's happening when I drag the window by the corner in order to resize it, but it's gone when I stop dragging. The flicker is most visible during the widgets demo, and it's not only the demo flickering, it's also the decorations that are flickering. 

> FYI: I have a big wayland PR coming with the goal of completely separating SHM and G2D (and EGL in the future)

That's great to hear. We also wanted to bring forward a draft PR for implementing dmabuf with CPU only, but noticed this flicker and started with trying to find the root cause first, as the flicker also happens with our patches.

**Comment by AndreCostaaa** [comment]
I will also check

If you could holf off on that PR until mine to avoid a lot of conflicts it would be amazing. It should be opened by next week and it should make it easier to maintain and to make sure this type of regressions don't happen

**Comment by nicusorcitu** [comment]
The flicker has to be fixed for lvgl 9.4.0. We can not wait for the redesign and hope to fix all the issues.
@anaGrad  would you please work with @AndreCostaaa to have this flicker fixed? Thanks!

**Comment by AndreCostaaa** [comment]
You're right, give me sometime to take a look, I need to setup input support on my imx93

**Comment by nicusorcitu** [comment]
As I understood is that some new patches (on top of this PR) have messed up.

**Comment by AndreCostaaa** [comment]
Does it happen with both direct and full render mode? Also if you're able to bisect it that would be amazing

IIRC the only updates to g2d was the final PR that we pushed just before the release. There were some other PRs around the way we handle physical outputs and minor refactorings but nothing that should cause flickering issues

**Comment by anaGrad** [comment]
It happens with both direct and full, and what's odd for me is that with our g2d pr, everything worked fine, so I am not sure what happened in the meantime. I tried narrowing down the issue, but it doesn't seem like any of the patches that came after are related.

**Comment by AndreCostaaa** [comment]
Is this what you're seeing? 

https://github.com/user-attachments/assets/1833e01c-9b17-4a69-834b-90dcf1d3c579

**Comment by anaGrad** [comment]
Not quite, here is a video of what I am seeing:

https://github.com/user-attachments/assets/530469bd-b5a4-4bd8-87a5-246c6c830909
