### PR TITLE
fix(sdl): do not dereferencing nullptr in lv_sdl_mouse_handler if an invalid windows id (0) has been received

### LINKED ISSUE #8608: Nullptr dereferencing in lv_sdl_mouse_handler if an invalid window id (0) has been received
### LVGL version

9.3.0

### Platform

SDL

### What happened?

We are trying to migrate from LVGL 9.2 to LVGL 9.3.

In our SDL application, when we press & hold the mouse and go outside of the window the application crashes.

It dies here: 
https://github.com/lvgl/lvgl/blob/2072d87b379cb0acdcbed127f692787ec71a1f8c/src/drivers/sdl/lv_sdl_mouse.c#L148

`win_id == 0` and therefore is `disp == 0` but the execution still reaches `lv_sdl_window_get_zoom`, which just does:

https://github.com/lvgl/lvgl/blob/2072d87b379cb0acdcbed127f692787ec71a1f8c/src/drivers/sdl/lv_sdl_window.c#L171-L172

but dsc is a nullptr.
 
The behavior changes from 9.2 to 9.3 somewhere else, how indev devices are organized. But in LVGL 9.2 "a random" indev is picked which does not have an `indev_dev` and so the routine does returns earlier.

https://github.com/lvgl/lvgl/blob/2072d87b379cb0acdcbed127f692787ec71a1f8c/src/drivers/sdl/lv_sdl_mouse.c#L137-L144

### PR DESCRIPTION
**Pull request by Viatorus**
Fixes #8608

Hard to reproduce. We are using multiple SDL displays at the same time and switching between them (using `lv_display_set_default`. Just checking if `disp` is valid solves it.

### CODE REVIEW

File: src/drivers/sdl/lv_sdl_mouse.c [hunk 1]
```diff
@@ -142,6 +142,7 @@ void lv_sdl_mouse_handler(SDL_Event * event)
     if(indev == NULL) return;
     lv_sdl_mouse_t * indev_dev = lv_indev_get_driver_data(indev);
     if(indev_dev == NULL) return;
+    if(disp == NULL) return;
```
Comment (AndreCostaaa) [inline src/drivers/sdl/lv_sdl_mouse.c]: Can the check be moved right after the `lv_sdl_get_disp_from_win_id` call?

No point checking for an indev if the display is NULL

**Review by AndreCostaaa — CHANGES_REQUESTED** [review]
Thank you for providing the fix, just a small nit

**Review by uLipe — DISMISSED** [review]

File: src/drivers/sdl/lv_sdl_mouse.c (hunk 1 above)
Comment (Viatorus) [reply src/drivers/sdl/lv_sdl_mouse.c]: done

**Review by AndreCostaaa — APPROVED** [review]

**Comment by AndreCostaaa** [comment]
Thank you 🚀

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thank you!
