### PR TITLE
fix(style): prevent overflow in style count

### LINKED ISSUE #8614: Integer overflow in in lv_obj_add_style() causing total memory corruption
### LVGL version

8.3.0

### Platform

custom board:
ESP32-WROOM-32UE-N16 CPU
ST7365P-G5 controller via LoyvanGFX library

ESP-IDF + vscode

but issue is platform-independent

### What happened?

`lv_obj_add_style()` in `lv_obj_style.c` 

problematic code:
```
    obj->style_cnt++;
    obj->styles = lv_mem_realloc(obj->styles, obj->style_cnt * sizeof(_lv_obj_style_t));

    uint32_t j;
    for(j = obj->style_cnt - 1; j > i ; j--) {
        obj->styles[j] = obj->styles[j - 1];
    }
```

what the function does:

- increments `obj->style_cnt`
- reallocates memory based on incremented style_cnt
- shifts all styles in the list to fit the new one

Problem:
`obj->style_cnt` is a bitfield with size of 6, meaning it's maximum value is 63. If `lv_obj_add_style()` is called more than 63 times on a given object, the folowing happens:

- `obj->style_cnt` overflows from 63 to 0
- in the subsequent loop, the loop counter is defined as  `uint32_t j; for(j = obj->style_cnt - 1;........`
- usually, since there is incrementation before, `obj->style_cnt` is >=1, but the overflow makes it 0
- this causes j to be = 0 -1 therefore causing underflow and now j=UINT32_MAX
- j is used as an array index and counting down
- this causes the code to attempt overwriting literally entire 32-bit address space, crash

So there is integer overflow causing an integer underflow and finally causing out of bounds write to memory

Image

Image

### How to reproduce?

call `lv_obj_add_style()` on a single object 64 or more times. Platform independent.

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Backport of https://github.com/lvgl/lvgl/pull/3727 to v8.3

Fixes #8614 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by AndreCostaaa** [comment]
CI failure is unrelated

**Review by kisvegabor — APPROVED** [review]

File: src/core/lv_obj_style.c [hunk 1]
```diff
@@ -75,6 +75,7 @@ void _lv_obj_style_init(void)
 
 void lv_obj_add_style(lv_obj_t * obj, lv_style_t * style, lv_style_selector_t selector)
 {
+    LV_ASSERT(obj->style_cnt < 63);
```
Comment (kisvegabor) [inline src/core/lv_obj_style.c]: Also return and add a warning in case the assets are disabled.

**Review by kisvegabor — CHANGES_REQUESTED** [review]

File: src/core/lv_obj_style.c (hunk 1 above)
Comment (AndreCostaaa) [reply src/core/lv_obj_style.c]: I wanted to align to how it's done in master. I can make the changes for both branches then

I also believe an ASSERT is too strong here, we can just check that condition and return early if it's not possible, what do you think?

**Comment by AndreCostaaa** [comment]
Just updated the PR, what do you think about this approach ? @kisvegabor 
If you like it I can update master afterwards

**Comment by kisvegabor** [comment]
What about keeping the hard coded value and doing this:
```c
/*Check for overflow*/
if(obj->style_cnt + 1 == 0) { ... }
```

**Comment by AndreCostaaa** [comment]
That doesn't work because `style_cnt + 1` will promote to a uint32_t and the check will never be true

See this:

```c
#include <stdint.h>
#include <stdio.h>

typedef struct {
	uint16_t style_cnt : 6;
} style;

int main()
{
	style s = { .style_cnt = 63 };

	printf("Style count is %d\n", s.style_cnt);
	
	if (s.style_cnt + 1 == 0) {
		printf("Max style count reached\n");
	} else {
		printf("Still have space for more styles\n");
		s.style_cnt++;
	}
	
	printf("Style count is now %d\n", s.style_cnt);
}
```
```terminal
❯ gcc main.c -o main
❯ ./main
Style count is 63
Still have space for more styles
Style count is now 0
```

**Review by kisvegabor — APPROVED** [review]
Oh, I see, thanks!

Let's merge it as it is. Probably it's not that important to argue about it too long. 

We should add it to v8.4 as well.

**Comment by AndreCostaaa** [comment]
Should we update master with this approach as well? Currently it's handled with an assertion

**Review by liamHowatt — APPROVED** [review]
