### PR TITLE
fix(draw_buf): align allocated buffers to LV_DRAW_BUF_ALIGN

### LINKED ISSUE #9868: Draw buf size not aligned correctly for PPA
### LVGL version

9.5.0

### Platform

ESP32

### What happened?

When filling rectangles e.g. for the indicator part of a slider, using the PPA feature on an ESP32 P4, the draw buf size is not rounded up to a multiple of LV_DRAW_BUF_ALIGN, which in this case is 64. This results in the ESP-IDF code throwing errors since the PPA can only operate on buffers whose start and end are properly aligned.
```
[11:05:26.616][E][lvgl:000]: [Error] lv_draw_ppa_fill: PPA fill failed: 258
[11:05:26.655]E (24829) cache: esp_cache_msync(122): start address: 0x48096680, or the size: 0x18f0 is(are) not aligned with cache line size (0x40)B
[11:05:26.666]E (24830) cache: esp_cache_msync(122): start address: 0x48096680, or the size: 0x18f0 is(are) not aligned with cache line size (0x40)B
[11:05:26.677][D][esp-idf:000]: E (24830) ppa_fill: ppa_do_fill(97): out.buffer addr or out.buffer_size not aligned to cache line size
[11:05:26.683][E][lvgl:000]: [Error] lv_draw_ppa_fill: PPA fill failed: 258
```

This is currently an issue for the adoption of LVGL 9.5 into ESPHome. The workaround is to turn off PPA.

The fix appears to be this:

```
diff --git a/src/draw/lv_draw_buf.c b/src/draw/lv_draw_buf.c
index 293f23d5e..62ba200d8 100644
--- a/src/draw/lv_draw_buf.c
+++ b/src/draw/lv_draw_buf.c
@@ -673,6 +673,7 @@ static uint32_t _calculate_draw_buf_size(uint32_t w, uint32_t h, lv_color_format
         size += LV_COLOR_INDEXED_PALETTE_SIZE(cf) * 4;
     }

+    size = LV_ROUND_UP(size, LV_DRAW_BUF_ALIGN);
     return size;
 }
```

### How to reproduce?

The following ESPHome config is for a Waveshare P4-NANO with the 10.1" screen. Compile and run this:

```
esphome run p4-10.yaml
```

and observe the logs.

```yaml

lvgl:
  byte_order: little_endian
  widgets:
    - slider:
        width: 21
        height: 200
        align: center
        indicator:
          radius: 0
        min_value: 0
        max_value: 255
        radius: 10
        knob:
          pad_top: -5

display:
  - platform: mipi_dsi
    id: main_display
    model: WAVESHARE-P4-NANO-10.1

esphome:
  name: p4-10
  friendly_name: P4 10.1

logger:
  hardware_uart: UART0

esp32:
  variant: esp32p4
  board: esp32-p4-evboard
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      execute_from_psram: true
      enable_idf_experimental_features: true

external_components:
  - source: github://pr#12312
    components: [font, image, lvgl]
    refresh: 1h

psram:
  mode: hex
  speed: 200MHz

esp_ldo:
  - voltage: 2.5V
    channel: 3

# -------------------------------------------
# Touchscreen GT911/GT9271 i2c
# -------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO07
    scl: GPIO08
    frequency: 400kHz
    scan: true

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: bus_a
    update_interval: 50ms
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: true
# -------------------------------------------
# Backlight
# -------------------------------------------
output:
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO26
    inverted: false
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms
```

Generated C Code for LVGL widget:

```
   lv_slider_t_id = lv_slider_create(lvgl_lvglcomponent_id->get_screen_active());
  lv_obj_set_style_align(lv_slider_t_id, LV_ALIGN_CENTER, LV_PART_MAIN);
  lv_obj_set_style_height(lv_slider_t_id, 200, LV_PART_MAIN);
  lv_obj_set_style_radius(lv_slider_t_id, 10, LV_PART_MAIN);
  lv_obj_set_style_width(lv_slider_t_id, 21, LV_PART_MAIN);
  lv_obj_set_style_radius(lv_slider_t_id, 0, LV_PART_INDICATOR);
  lv_obj_set_style_pad_top(lv_slider_t_id, -5, LV_PART_KNOB);
  lv_slider_set_range(lv_slider_t_id, 0, 255);
  lv_slider_set_mode(lv_slider_t_id, LV_SLIDER_MODE_NORMAL);
```

And lv_conf.h used:
```
#define LV_ATTRIBUTE_MEM_ALIGN_SIZE 0
#define LV_BUILD_DEMOS 0
#define LV_BUILD_EXAMPLES 0
#define LV_COLOR_16_SWAP 0
#define LV_COLOR_CHROMA_KEY lv_color_make(0, 4, 0)
#define LV_COLOR_DEPTH 16
#define LV_DRAW_BUF_ALIGN 64
#define LV_DRAW_BUF_STRIDE_ALIGN 1
#define LV_DRAW_SW_COMPLEX 1
#define LV_DRAW_SW_DRAW_UNIT_CNT 0
#define LV_DRAW_SW_SUPPORT_A8 0
#define LV_DRAW_SW_SUPPORT_AL88 0
#define LV_DRAW_SW_SUPPORT_ARGB8888 0
#define LV_DRAW_SW_SUPPORT_I1 0
#define LV_DRAW_SW_SUPPORT_L8 0
#define LV_DRAW_SW_SUPPORT_PREMULTIPLIED 0
#define LV_DRAW_SW_SUPPORT_RGB565 1
#define LV_DRAW_SW_SUPPORT_RGB565A8 0
#define LV_DRAW_SW_SUPPORT_RGB888 1
#define LV_DRAW_SW_SUPPORT_SWAPPED 0
#define LV_DRAW_SW_SUPPORT_XRGB8888 0
#define LV_FILE_EXPLORER_QUICK_ACCESS 0
#define LV_FONT_DEFAULT &lv_font_montserrat_14
#define LV_FONT_MONTSERRAT_14 1
#define LV_GRADIENT_MAX_STOPS 2
#define LV_IME_PINYIN_USE_DEFAULT_DICT 0
#define LV_IME_PINYIN_USE_K9_MODE 0
#define LV_LABEL_LONG_TXT_HINT 0
#define LV_LABEL_TEXT_SELECTION 0
#define LV_LINUX_DRM_USE_EGL 0
#define LV_LINUX_FBDEV_MMAP 0
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_USE_FILE_LINE 0
#define LV_LOG_USE_TIMESTAMP 0
#define LV_PROFILER_BUILTIN_DEFAULT_ENABLE 0
#define LV_PROFILER_CACHE 0
#define LV_PROFILER_DECODER 0
#define LV_PROFILER_DRAW 0
#define LV_PROFILER_EVENT 0
#define LV_PROFILER_FONT 0
#define LV_PROFILER_FS 0
#define LV_PROFILER_INDEV 0
#define LV_PROFILER_LAYOUT 0
#define LV_PROFILER_REFR 0
#define LV_PROFILER_TIMER 0
#define LV_SDL_USE_EGL 0
#define LV_TEST_SCREENSHOT_CREATE_REFERENCE_IMAGE 0
#define LV_THEME_DEFAULT_GROW 0
#define LV_USE_ANIMIMG 0
#define LV_USE_ARC 0
#define LV_USE_ARCLABEL 0
#define LV_USE_BAR 1
#define LV_USE_BTNMATRIX_BTN 0
#define LV_USE_BUTTON 0
#define LV_USE_BUTTONMATRIX 0
#define LV_USE_CALENDAR 0
#define LV_USE_CALENDAR_HEADER_ARROW 0
#define LV_USE_CALENDAR_HEADER_DROPDOWN 0
#define LV_USE_CANVAS 0
#define LV_USE_CHART 0
#define LV_USE_CHECKBOX 0
#define LV_USE_CONTAINER 0
#define LV_USE_DRAW_G2D 0
#define LV_USE_DRAW_PXP 0
#define LV_USE_DRAW_SW 1
#define LV_USE_DROPDOWN 0
#define LV_USE_DROPDOWN_LIST 0
#define LV_USE_EGL 0
#define LV_USE_FLEX 0
#define LV_USE_FONT_PLACEHOLDER 1
#define LV_USE_FREERTOS_TASK_NOTIFY 0
#define LV_USE_G2D_DRAW_THREAD 0
#define LV_USE_GENERIC_MIPI 0
#define LV_USE_GRID 0
#define LV_USE_IMAGE 0
#define LV_USE_KEYBOARD 0
#define LV_USE_LABEL 1
#define LV_USE_LED 0
#define LV_USE_LINE 0
#define LV_USE_LIST 0
#define LV_USE_LOG 1
#define LV_USE_LV_TILEVIEW_TILE_T 0
#define LV_USE_LZ4 0
#define LV_USE_MENU 0
#define LV_USE_METER 0
#define LV_USE_MSGBOX 0
#define LV_USE_NUTTX_MOUSE_MOVE_STEP 0
#define LV_USE_OBJ 0
#define LV_USE_OBJ_ID_BUILTIN 0
#define LV_USE_OBJ_PROPERTY_NAME 0
#define LV_USE_OBSERVER 0
#define LV_USE_PAGE 0
#define LV_USE_PPA 1
#define LV_USE_PROFILER_BUILTIN 0
#define LV_USE_PXP_DRAW_THREAD 0
#define LV_USE_QRCODE 0
#define LV_USE_ROLLER 0
#define LV_USE_SCALE 0
#define LV_USE_SLIDER 1
#define LV_USE_SPAN 0
#define LV_USE_SPINBOX 0
#define LV_USE_SPINNER 0
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CUSTOM
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STYLE 1
#define LV_USE_SWITCH 0
#define LV_USE_TABLE 0
#define LV_USE_TABVIEW 0
#define LV_USE_TEXTAREA 0
#define LV_USE_THEME_DEFAULT 1
#define LV_USE_THEME_MONO 0
#define LV_USE_THEME_SIMPLE 0
#define LV_USE_THORVG 0
#define LV_USE_TILEVIEW 0
#define LV_USE_USER_DATA 1
#define LV_USE_WIN 0
#define LV_VG_LITE_THORVG_16PIXELS_ALIGN 0
#define LV_VG_LITE_USE_BOX_SHADOW 0
#define LV_WAYLAND_USE_EGL 0
#define LV_WAYLAND_USE_G2D 0
#define LV_WAYLAND_USE_SHM 0
#define LV_WIDGETS_HAS_DEFAULT_VALUE 0
```

### PR DESCRIPTION
**Pull request by clydebarrow**
Fixes #9868 

Ensure draw bufs are not only allocated on a correct boundary, but the length is also correctly aligned to a multiple of LV_DRAW_BUF_ALIGN.

This fixes errors with ESP32-P4 PPA rect fills.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

File: src/draw/lv_draw_buf.c [hunk 1]
```diff
@@ -673,6 +673,7 @@ static uint32_t _calculate_draw_buf_size(uint32_t w, uint32_t h, lv_color_format
         size += LV_COLOR_INDEXED_PALETTE_SIZE(cf) * 4;
     }
 
+    size = LV_ROUND_UP(size, LV_DRAW_BUF_ALIGN);
     return size;
```
Comment (FASTSHIFT) [inline src/draw/lv_draw_buf.c]: `return LV_ROUND_UP(size, LV_DRAW_BUF_ALIGN);`

Comment (youkorr) [reply src/draw/lv_draw_buf.c]: PPA cache sync: data_size rounded up to LV_DRAW_BUF_ALIGN before calling esp_cache_msync()

**Comment by FASTSHIFT** [comment]
Could you please add a test case to [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) to intercept subsequent issues?

File: src/draw/lv_draw_buf.c (hunk 1 above)
Comment (FASTSHIFT) [reply src/draw/lv_draw_buf.c]: This expression is equivalent and can reduce redundant assignments.

File: src/draw/lv_draw_buf.c [hunk 2]
```diff
@@ -673,6 +673,7 @@ static uint32_t _calculate_draw_buf_size(uint32_t w, uint32_t h, lv_color_format
         size += LV_COLOR_INDEXED_PALETTE_SIZE(cf) * 4;
     }
 
+    size = LV_ROUND_UP(size, LV_DRAW_BUF_ALIGN);
```
[the remark this answers is not in the document]
Comment (clydebarrow) [reply src/draw/lv_draw_buf.c]: `lv_draw_buf_init` is passed a size, it doesn't allocate memory. `lv_draw_buf_from_image` is another issue.

**Comment by axos88** [comment]
Thanks for the pull request, approved.

**Review by axos88 — APPROVED** [review]

**Comment by axos88** [comment]
Can you please fix the failing test, and add a regression test for this bug?

**Review by axos88 — CHANGES_REQUESTED** [review]
please fix the failing test and add a regression test.

**Comment by clydebarrow** [comment]
> please fix the failing test and add a regression test.

It's not clear to me why the test is failing, or even what the failure is - the log shows misaligned accesses and memory leaks but it's hard to see how the change could cause either of those.

I have been unable to get the tests to run on my desktop (Mac M1) to do any local testing. It looks like the tests are intended to run on x86 Linux only.

**Comment by youkorr** [comment]
Your patch is good but too low in the stack. Either you reduce the scope to the backend PPA (Espressif solution / yours), or it completes lv_draw_buf_init plus tests

**Comment by youkorr** [comment]
Why the CI sanitizer fires even though the visual tests still pass

Your LV_ROUND_UP in _calculate_draw_buf_size() is correct in isolation, but the function is only one of three ways draw_buf->data_size gets set:

lv_draw_buf_create_ex goes through _calculate_draw_buf_size  data_size is now padded.
lv_draw_buf_init  stores the caller-provided data_size verbatim still unpadded.
lv_draw_buf_from_image delegates to _init → still unpadded.
This breaks two invariants that the test suite (with -fsanitize=address) actively checks:

lv_draw_buf_dup_ex copies LV_MIN(src->data_size, dst->data_size) bytes. When both buffers come from _create, LV_MIN now includes the LV_DRAW_BUF_ALIGN - 1 padding tail. buf_malloc uses malloc, not calloc, so that tail is uninitialized ASan reports "use of uninitialized value" (shows up as "misaligned access" in some ASan output formats).
lv_draw_buf_reshape / _adjust_stride compare _calculate_draw_buf_size(...) (padded) against draw_buf->data_size (raw if the buffer was initialized or imported). The compare now returns "too small" even when the underlying allocation is fine, so callers fall back to reallocating and occasionally drop the old buffer → the leak ASan reports.
Two ways to fix:

Apply the round-up at the same three setters: _calculate_draw_buf_size + lv_draw_buf_init (round up before storing in data_size) + lv_draw_buf_from_image. Then all paths share the invariant. This also requires updating any test reference that encodes a raw data_size.
Move the round-up out of the generic allocator entirely and apply it at the hardware boundary (the ESP-IDF PPA backend), where it's actually needed. That's what esp_lvgl_port does in components/esp_lvgl_port/src/common/ppa/lcd_ppa.c via ALIGN_UP(buffer_size, CONFIG_CACHE_L2_CACHE_LINE_SIZE). Keeps the LVGL core invariant intact, no test churn, still fixes #9868. Working implementation: youkorr/lvgl_9.5@<sha>.
For reproducing locally on M1: the standard runner won't enable ASan on Darwin/ARM. Either use a Linux Docker image (docker run --rm -v $PWD:/lvgl -w /lvgl/tests ubuntu:24.04 bash -c "apt install -y cmake gcc g++ python3 && ./main.py test"), or configure clang manually with -fsanitize=address -fno-omit-frame-pointer.

**Comment by clydebarrow** [comment]
> Either use a Linux Docker image

So it turns out there is already a Dockerfile under /tests for this very purpose. Running now.

**Comment by clydebarrow** [comment]
> Can you please fix the failing test, and add a regression test for this bug?

Done.

**Review by AndreCostaaa — APPROVED** [review]
Amazing. Thank you 💯

**Review by axos88 — APPROVED** [review]
