### PR TITLE
fix(spinbox): fix stack corruption

### LINKED ISSUE #9255: Stack corruption when spinbox min/max values have more than 5 digits
### LVGL version

v9.4.0

### Platform

Visual Studio simulator

### What happened?

When lv_spinbox_set_range() is called with min/max values greater than 5 digits (which seems to be default), a stack corruption occurs inside lv_spinbox_updatevalue() function. If lv_spinbox_set_digit_format() is called before and sets 6 digits, the issue does not occur.

### How to reproduce?

```c
static lv_obj_t* spinbox = lv_spinbox_create(lv_screen_active());
lv_spinbox_set_range(spinbox, 100000, 200000);
lv_spinbox_set_digit_format(spinbox, 6, 0);
```
Workaround: call lv_spinbox_set_digit_format() _before_ lv_spinbox_set_range()

### PR DESCRIPTION
**Pull request by pe-jot**
Only add leading zeros when calculation returns a positive number.

Fixes #9255

When the number of digits is greater than currently configured, it happens that the number of zeros to add turns negative. The if() clause fails due to lack of an appropriate comparator.

_Ready_

### CODE REVIEW

**Review by AndreCostaaa — APPROVED** [review]

**Comment by FASTSHIFT** [comment]
Could you help add a test case to cover this situation? ;)

**Review by uLipe — CHANGES_REQUESTED** [review]
LGTM, +1 to add a test case.

Thank you for the fix!

**Comment by pe-jot** [comment]
I had a look at the tests, but unfortunately I am not sure how to test for the exception not occurring.
What I have seen with the Visual Studio build was, that the exception only occurred with a debugger attached. Without any debugger, it did not show any issues (as far as I have observed).
There is also another pull request #9263 which obviously comes from someone more capable than I am ;-)

**Comment by vwheeler63** [comment]
> There is also another pull request #9263 which obviously comes from someone more capable than I am ;-)

cc:  @AndreCostaaa @uLipe @kisvegabor 

Hello, Philipp! ( @pe-jot )

When I submitted PR #9263, I hadn't realized you had submitted this one.  My oversight.  This is a nice simple solution.

I worry, however, that it leaves a situation where `digit_count` can be smaller than the range values, leaving the conflict in place.  My approach works instead on eliminating the conflict, but this is a point which probably should be discussed, because doing the latter is more complicated.  The point that perhaps deserves discussion is:

### What is the DESIGN INTENTION of the Spinbox?   Is it:

1. to allow the conflict between `digit_count` and the range values, which keeps the code simple (e.g. in the functions that impact them), or

2. to prevent the conflict, and keep the 3 values in a consistent state after each public API call?

If the DESIGN INTENTION is (1), then this is the correct PR for it.  If it is (2), then PR #9263 handles it that way.

Awaiting your reply(s).


### Edit:  Food for thought:

(2) follows O-O theory:  the conflict-prevention functions as the "class invariant" (condition(s) that must always be true before and after any public API calls).

Also, an assertion right before that IF block, like

```c
LV_ASSERT(spinbox->digit_count >= (uint32_t)digits_len);
```

would make it clear that the DESIGN INTENTION is to prevent the conflict.  (If that is the case.)

Edit:  PR #9263 also handles several other problems like correcting range checking `digit_count`, which if 0 causes problems later, and range checking the range values.

Edit:  Another thought:  given the design of the UI, all digits in the range must always be displayed, so the `digit_count` should perhaps be ENTIRELY controlled by the range, instead of being independently settable.  That would solve the problem completely by a slight (although breaking) API change.  (However, this would eliminate Spinbox's ability to have additional leading zeros outside the range, which might be a design point and certainly doesn't do any harm.)

**Comment by pe-jot** [comment]
Dear Victor ( @vwheeler63 ),

Thank you for your detailed contribution!

Admittedly, I am quite new to LVGL, so I am afraid that I am not the right guy to discuss the design intentions of the spinbox with. But, my gut feeling was right that there is more to that than my simple fix of the if-clause, and I'm glad that you've picked it up!

Anyway, I will share my thoughts here:

- Going the approach (2) to keep the values in sync maybe will imply some (from user perspective) unexpected behavior, as one will need at least 2 function calls to configure the range values completely (1 for min/max and 1 for digit setting).

- At this point, please also allow for scenarios where values are set dynamically, not only once during the initial setup phase, as it was in my case.

- When having a look at the spinbox code the first time, my initial thought was: "Why is it already updating when I haven't completed my configuration?". Maybe, it would be an idea to prevent updating/rendering of widgets through some API functions (I think .NET Windows Forms has such a functionality).

**Comment by vwheeler63** [comment]
Hi, Philipp!  ( @pe-jot )

Your points are good ones and well taken.  Let's see what the other CC'd individuals, have to say.  The original creator is among them.  Talk with you soon!

Kind regards,
Vic

**Comment by kisvegabor** [comment]
Hi All,

Thank you for opening the PR.

It can happen that there are parameters that are depending on each other. In this case
- we need to make sure that we no crash happens
- we should add warning logs if needed

So I'm ok with the simpler solution. It can be the user's responsibility to keep these consistent.

**Review by AndreCostaaa — DISMISSED** [review]

**Review by kisvegabor — DISMISSED** [review]

**Comment by kisvegabor** [comment]
I'll add a test today.

**Review by kisvegabor — DISMISSED** [review]

**Comment by kisvegabor** [comment]
Test is added, @uLipe, @AndreCostaaa PTAL

File: examples/widgets/canvas/lv_example_canvas_1.c [hunk 1]
```diff
@@ -25,7 +25,7 @@ void lv_example_canvas_1(void)
     lv_draw_label_dsc_t label_dsc;
     lv_draw_label_dsc_init(&label_dsc);
     label_dsc.color = lv_palette_main(LV_PALETTE_ORANGE);
-    label_dsc.text = "Some text on text canvas";
+    label_dsc.text = lv_strdup("Some text on text canvas");
```
Comment (AndreCostaaa) [inline examples/widgets/canvas/lv_example_canvas_1.c]:
```suggestion
    label_dsc.text = "Some text on text canvas";
```

**Review by AndreCostaaa — COMMENTED** [review]
File changed by mistake

File: tests/src/test_cases/widgets/test_spinbox.c [hunk 2]
```diff
@@ -305,4 +305,13 @@ void test_spinbox_zero_crossing(void)
     TEST_ASSERT_EQUAL(13, lv_spinbox_get_value(spinbox_events));
 }
 
+void test_spinbox_few_gigits(void)
```
Comment (AndreCostaaa) [inline tests/src/test_cases/widgets/test_spinbox.c]:
```suggestion
void test_spinbox_few_digits(void)
```

**Review by AndreCostaaa — APPROVED** [review]

**Review by liamHowatt — APPROVED** [review]

**Comment by liamHowatt** [comment]
Merging blocked pending @uLipe's review.

**Review by uLipe — APPROVED** [review]
