### PR TITLE
fix(tjpgd): Fixed memory leak if opening JPEG image failed.

### LINKED ISSUE #8579: Memory leak in Tiny JPEG Decompressor (TJPGD)
### LVGL version

v9.3.0

### Platform

ESP32-S3-WROOM-1-R8N16 with FreeRTOS

### What happened?

Memory leak if JPEG file failed to open.

By mistake i tried to open progressive JPEG file which is not supported by TJPGD.
While trying to find the cause i found a memory leak.

The application tried to repeatedly open the unsupported file, which after some time resulted in lv_malloc failing to allocate more memory, as memory was leaking.

The cause is the code in file lv_tjpgd.c:
```
    uint8_t * workb_temp = lv_malloc(TJPGD_WORKBUFF_SIZE);
    JDEC * jd = lv_malloc(sizeof(JDEC));
    dsc->user_data = jd;
    JRESULT rc = jd_prepare(jd, input_func, workb_temp, (size_t)TJPGD_WORKBUFF_SIZE, f);
    if(rc) return LV_RESULT_INVALID;

    dsc->header.cf = LV_COLOR_FORMAT_RGB888;
    dsc->header.w = jd->width;
    dsc->header.h = jd->height;
    dsc->header.stride = jd->width * 3;

    if(rc != JDR_OK) {
        lv_free(workb_temp);
        lv_free(jd);
        return LV_RESULT_INVALID;
    }

    return LV_RESULT_OK;
```
or specifically line 191: `if(rc) return LV_RESULT_INVALID;`
As a result the second check that actually frees the memory is never reached.

suggestion:
Replace the first check with the second one, add release of file information, and move assignment of allocated object to decoder description to happen only on success:
```
    uint8_t * workb_temp = lv_malloc(TJPGD_WORKBUFF_SIZE);
    JDEC * jd = lv_malloc(sizeof(JDEC));
    JRESULT rc = jd_prepare(jd, input_func, workb_temp, (size_t)TJPGD_WORKBUFF_SIZE, f);
    if(rc != JDR_OK) {
        lv_free(workb_temp);
        lv_free(jd);
        lv_free(f);
        return LV_RESULT_INVALID;
    }

    dsc->user_data = jd;

    dsc->header.cf = LV_COLOR_FORMAT_RGB888;
    dsc->header.w = jd->width;
    dsc->header.h = jd->height;
    dsc->header.stride = jd->width * 3;

    return LV_RESULT_OK;
```

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by akorsunski**
Fixes #8579

Fixes memory leak that occurs, if Tiny JPEG Decompressor (TJPGD)  failed to open JPEG image.
The code was missing memory release of allocated lv_fs_file_t structure and there was a premature return.

### CODE REVIEW

**Review by uLipe — DISMISSED** [review]

File: src/libs/tjpgd/lv_tjpgd.c [hunk 1]
```diff
@@ -186,21 +187,21 @@ static lv_result_t decoder_open(lv_image_decoder_t * decoder, lv_image_decoder_d
```
Comment (liamHowatt) [inline src/libs/tjpgd/lv_tjpgd.c:190]: Can you also please add an "else free f, return" here? Execution continues assuming the file is open while it may not be.

**Review by liamHowatt — COMMENTED** [review]
Nicely done, thanks.

File: src/libs/tjpgd/lv_tjpgd.c (hunk 1 above)
Comment (akorsunski) [reply src/libs/tjpgd/lv_tjpgd.c:190]: Added. Actually such condition should not be reachable in normal workflow (decoder_open should only be called if decoder_info passed). But I agree that it is good as a sanity check.

**Review by uLipe — DISMISSED** [review]

**Review by liamHowatt — DISMISSED** [review]
Oh wow you caught even more! Nice.

**Review by liamHowatt — DISMISSED** [review]

**Comment by liamHowatt** [comment]
Typically, we put `LV_ASSERT_MALLOC(p);` right after `lv_malloc` so that users can crash immediately, if they want, if any allocation fails.

**Review by uLipe — APPROVED** [review]

File: src/libs/tjpgd/lv_tjpgd.c [hunk 2]
```diff
@@ -182,25 +187,33 @@ static lv_result_t decoder_open(lv_image_decoder_t * decoder, lv_image_decoder_d
...
+            return LV_RESULT_INVALID;
+        }
+    }
+    else {
+        lv_free(f);
+        return LV_RESULT_INVALID;
     }
 
     uint8_t * workb_temp = lv_malloc(TJPGD_WORKBUFF_SIZE);
     JDEC * jd = lv_malloc(sizeof(JDEC));
```
[the remark this answers is not in the document]
Comment (akorsunski) [reply src/libs/tjpgd/lv_tjpgd.c:192]: Rewritten this part of code

**Review by FASTSHIFT — APPROVED** [review]
